/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as PaymentRouteImport } from "./routes/payment";
import { Route as AuthRouteImport } from "./routes/auth";
import { Route as AdminRouteImport } from "./routes/admin";

const PaymentRoute = PaymentRouteImport.update({
  id: "/payment",
  path: "/payment",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any);
import { Route as RegisterRouteImport } from "./routes/register";

const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/admin": typeof AdminRoute;
  "/auth": typeof AuthRoute;
  "/payment": typeof PaymentRoute;
}
export interface FileRoutesByTo {
  "/admin": typeof AdminRoute;
  "/auth": typeof AuthRoute;
  "/payment": typeof PaymentRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/admin": typeof AdminRoute;
  "/auth": typeof AuthRoute;
  "/payment": typeof PaymentRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/admin" | "/auth" | "/payment";
  fileRoutesByTo: FileRoutesByTo;
  to: "/admin" | "/auth" | "/payment";
  id: "__root__" | "/admin" | "/auth" | "/payment";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRoute;
  AuthRoute: typeof AuthRoute;
  PaymentRoute: typeof PaymentRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/payment": {
      id: "/payment";
      path: "/payment";
      fullPath: "/payment";
      preLoaderRoute: typeof PaymentRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth": {
      id: "/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin": {
      id: "/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  PaymentRoute: PaymentRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
